from datetime import datetime
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch

def generate_pdf(
    filename,
    predicted_score,
    performance,
    attendance,
    summary,
    strengths,
    recommendations
):
    # Setup document
    doc = SimpleDocTemplate(filename)
    styles = getSampleStyleSheet()

    # Create distinct styles to avoid modifying the global defaults directly
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Title'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        alignment=TA_CENTER,
        textColor=colors.darkblue
    )

    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.darkblue,
        spaceAfter=6
    )
    
    body_style = styles["BodyText"]
    
    # Custom cell style for table headers/left column
    table_label_style = ParagraphStyle(
        'TableLabel',
        parent=body_style,
        fontName='Helvetica-Bold'
    )

    story = []

    # ----------------------------
    # Title & Subtitle
    # ----------------------------
    story.append(Paragraph("EduPredict AI", title_style))
    story.append(Paragraph("Student Performance Report", heading_style))
    story.append(Spacer(1, 0.3 * inch))

    # ----------------------------
    # Report Information Table
    # ----------------------------
    report_id = datetime.now().strftime("SPR-%Y%m%d-%H%M%S")
    report_date = datetime.now().strftime("%d %B %Y")

    # Wrapping strings in Paragraphs ensures text wraps safely inside cells
    info = [
        [Paragraph("Report ID", table_label_style), Paragraph(report_id, body_style)],
        [Paragraph("Generated On", table_label_style), Paragraph(report_date, body_style)],
        [Paragraph("Predicted Score", table_label_style), Paragraph(f"{predicted_score:.2f}/100", body_style)],
        [Paragraph("Performance", table_label_style), Paragraph(performance, body_style)],
        [Paragraph("Attendance", table_label_style), Paragraph(f"{attendance}%", body_style)]
    ]

    # Column widths sizing up to a standard page width nicely
    table = Table(info, colWidths=[2.2 * inch, 3.5 * inch])
    table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (0, -1), colors.lightblue),
        ("VALIGN", (0, 0), (-1, -1), 'MIDDLE'),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
    ]))

    story.append(table)
    story.append(Spacer(1, 0.3 * inch))

    # ----------------------------
    # Summary
    # ----------------------------
    story.append(Paragraph("Prediction Summary", heading_style))
    story.append(Paragraph(summary, body_style))
    story.append(Spacer(1, 0.2 * inch))

    # ----------------------------
    # Strengths
    # ----------------------------
    story.append(Paragraph("Strengths", heading_style))
    for item in strengths:
        # Added a clean bullet formatting
        story.append(Paragraph(f"• {item}", body_style))

    story.append(Spacer(1, 0.2 * inch))

    # ----------------------------
    # Recommendations
    # ----------------------------
    story.append(Paragraph("Recommendations", heading_style))
    if recommendations:
        for item in recommendations:
            story.append(Paragraph(f"• {item}", body_style))
    else:
        story.append(
            Paragraph(
                "Excellent! No additional recommendations. Keep up the good work.",
                body_style
            )
        )

    story.append(Spacer(1, 0.4 * inch))

    # ----------------------------
    # Footer
    # ----------------------------
    footer_style = ParagraphStyle(
        'FooterStyle',
        parent=styles['Normal'],
        fontSize=9,
        leading=12,
        textColor=colors.dimgrey
    )
    
    story.append(
        Paragraph(
            "<b>Generated by EduPredict AI</b><br/>"
            "Developed by Aashika Sankar<br/>"
            "M.Sc. Computer Science<br/>"
            "Central University of Kerala",
            footer_style
        )
    )

    doc.build(story)

# --- Example Usage Run ---
if __name__ == "__main__":
    generate_pdf(
        filename="student_report.pdf",
        predicted_score=85.50,
        performance="Good",
        attendance=92,
        summary="The student shows steady progress across core subjects. High assignment completion rates are positively impacting final outcomes.",
        strengths=["Strong analytical reasoning", "Excellent laboratory execution skills"],
        recommendations=["Focus on time management during major exams", "Participate in advanced discussion groups"]
    )
    print("PDF generated successfully!")