from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.units import inch

from datetime import datetime


def generate_pdf(
    filename,
    predicted_score,
    performance,
    attendance,
    summary,
    strengths,
    recommendations
):

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title = styles["Title"]
    title.alignment = TA_CENTER
    title.textColor = colors.darkblue

    heading = styles["Heading2"]
    heading.textColor = colors.darkblue

    story = []

    # ----------------------------
    # Title
    # ----------------------------

    story.append(Paragraph("EduPredict AI", title))
    story.append(Paragraph("Student Performance Report", heading))
    story.append(Spacer(1, 0.3 * inch))

    # ----------------------------
    # Report Information
    # ----------------------------

    report_id = datetime.now().strftime("SPR-%Y%m%d-%H%M%S")
    report_date = datetime.now().strftime("%d %B %Y")

    info = [
        ["Report ID", report_id],
        ["Generated On", report_date],
        ["Predicted Score", f"{predicted_score:.2f}/100"],
        ["Performance", performance],
        ["Attendance", f"{attendance}%"]
    ]

    table = Table(info, colWidths=[2.2 * inch, 3.5 * inch])

    table.setStyle(TableStyle([
        ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
        ("BACKGROUND", (0,0), (0,-1), colors.lightblue),
        ("FONTNAME", (0,0), (-1,-1), "Helvetica"),
        ("BOTTOMPADDING", (0,0), (-1,-1), 8)
    ]))

    story.append(table)
    story.append(Spacer(1, 0.3 * inch))

    # ----------------------------
    # Summary
    # ----------------------------

    story.append(Paragraph("Prediction Summary", heading))
    story.append(Paragraph(summary, styles["BodyText"]))
    story.append(Spacer(1, 0.2 * inch))

    # ----------------------------
    # Strengths
    # ----------------------------

    story.append(Paragraph("Strengths", heading))

    for item in strengths:
        story.append(Paragraph(f" • {item}", styles["BodyText"]))

    story.append(Spacer(1, 0.2 * inch))

    # ----------------------------
    # Recommendations
    # ----------------------------

    story.append(Paragraph("Recommendations", heading))

    if recommendations:
        for item in recommendations:
            story.append(Paragraph(f" • {item}", styles["BodyText"]))
    else:
        story.append(
            Paragraph(
                "Excellent! No additional recommendations. Keep up the good work.",
                styles["BodyText"]
            )
        )

    story.append(Spacer(1, 0.4 * inch))

    # ----------------------------
    # Footer
    # ----------------------------

    story.append(
        Paragraph(
            "<b>Generated by EduPredict AI</b><br/>"
            "Developed by Aashika Sankar<br/>"
            "M.Sc. Computer Science<br/>"
            "Central University of Kerala",
            styles["Normal"]
        )
    )

    doc.build(story)